Implements thesis processing form
MITLibraries/thing pull request #714
Opened 2021-05-25 14:22 UTC by matt-bernhardt

#### Developer

- [ ] All new ENV is documented in README
- [ ] All new ENV has been added to Heroku Pipeline, Staging and Prod
- [ ] ANDI or Wave has been run in accordance to
      [our guide](https://mitlibraries.github.io/guides/basics/a11y.html) and
      all issues introduced by these changes have been resolved or opened as new
      issues (link to those issues in the Pull Request details above)
- [ ] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer

- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

#### Requires database migrations?

NO

#### Includes new or updated dependencies?

NO

2021-06-07 18:03 UTC, JPrevost requested changes
I'd prefer we update the `active_holds?` and `authors_graduated?` to return booleans to match the typical expectations in ruby applications. If you feel that leads to significantly more logic where the data is used in the application, let me know and we can discuss it further.

2021-06-07 18:11 UTC, matt-bernhardt commented on test/models/thesis_test.rb
> +  test 'authors_graduated? returns "No" if any author has not graduated' do
I can add this test, sure

2021-06-07 18:12 UTC, matt-bernhardt commented on app/models/thesis.rb
> +  # holds with a status of either 'active' or 'expired'. A false/"No" is
Yeah, I was on the fence about whether this method should just return true/false and leave the formatting of that response to the view layer - so thanks for the nudge in this direction. I'll make the change - it shouldn't be too hard to update the view accordingly.

2021-06-07 18:15 UTC, matt-bernhardt commented on app/views/thesis/_department_thesis_fields.html.erb
> +  <aside><%= link_to_remove_association "Remove this department", f %></aside>
This... yeah. There's a lot of potential complexity here, and I'm worried about overly complex technical implementations when what's needed is a user who doesn't do really illogical things.

Many, many years ago I worked on a UI widget that might be preferrable - http://jsfiddle.net/matt_bernhardt/22kUX/ - but I agree with at most making this a ticket to tackle in the future, if it proves needed.

2021-06-09 19:21 UTC, matt-bernhardt commented on app/views/thesis/_department_thesis_fields.html.erb
> +  <aside><%= link_to_remove_association "Remove this department", f %></aside>
I've created ticket https://mitlibraries.atlassian.net/browse/ETD-350 in our backlog to record the need for this work.

2021-06-09 19:22 UTC, matt-bernhardt commented
Ok, I think I've now responded to the three requested changes. Two of them have been addressed with code changes that should solve the issue, while the third has spawned a new ticket in our backlog.

2021-06-09 19:45 UTC, JPrevost approved these changes

2021-06-09 20:00 UTC, merged