Generate email report for data registrar import jobs
MITLibraries/thing pull request #758
Opened 2021-08-03 17:51 UTC by jazairi

#### Why these changes are being introduced:

Processors and thesis admins need to see summary data about the
registrar import job, especially if there are any issues with it.
The job currently logs much of this information, but an email report
would be more useful for stakeholders to review.

#### Relevant ticket(s):

* https://mitlibraries.atlassian.net/browse/ETD-354
* https://mitlibraries.atlassian.net/browse/ETD-348
* https://mitlibraries.atlassian.net/browse/ETD-371

#### How this addresses that need:

This adds some data collection to the import job, as well as a mailer
that reports the following data:

* Number of theses in the job
* Number of theses processed
* Errors found (total number and list)
* New DLCs added (total number and list)
* New degrees added (total number and list)
* Number of new users
* Number of new theses
* Number of updated theses

#### Side effects of this change:

* The email is sent in the job rather than the controller so as to
access the results, but we may need to move that up to the controller
if it doesn't work.
* For new DLCs and degrees, we are dumping the results of the `inspect`
method, which may be difficult to read for end users. We should take a
look at this in the PR build before merging.

#### Developer

- [x] All new ENV is documented in README
- [x] All new ENV has been added to Heroku Pipeline, Staging and Prod
- [x] ANDI or Wave has been run in accordance to
      [our guide](https://mitlibraries.github.io/guides/basics/a11y.html) and
      all issues introduced by these changes have been resolved or opened as new
      issues (link to those issues in the Pull Request details above)
- [ ] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer

- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

#### Requires database migrations?

NO

#### Includes new or updated dependencies?

NO

2021-08-04 21:25 UTC, JPrevost commented on app/views/report_mailer/registrar_import_email.html.erb
> +      <li><%= link_to degree.name_dw, "/admin/degrees/#{degree.id}" %></li>
I think these links will be problematic in an actual sent email (haven't confirmed yet).

We may need to look into this:
https://edgeguides.rubyonrails.org/action_mailer_basics.html#generating-urls-in-action-mailer-views

2021-08-05 19:21 UTC, JPrevost requested changes
A couple of missing `</li>` in the template and some suggested (not required) ideas on how to assert/refute true/false in tests.

2021-08-05 19:21 UTC, JPrevost commented on test/models/thesis_test.rb
> +    assert_equal false, preexisting_thesis.new_thesis?
You may want to consider using syntax like  `refute(preexisting_thesis.new_thesis?)` for true / false checks in mini_test.

https://minitest.rubystyle.guide/#refute-false

and 

https://minitest.rubystyle.guide/#assert-truthy

2021-08-05 19:21 UTC, JPrevost commented on app/views/report_mailer/registrar_import_email.html.erb
> +  <li>Total theses in job: <%= @results[:read] %>
couple of missing `</li>` in this block

2021-08-05 19:46 UTC, jazairi commented on app/mailers/report_mailer.rb
> +         to: ENV['THESIS_ADMIN_EMAIL'],
Good call. This reminds me that production.rb now includes a `MAILER_URL` variable that I don't think we need, so I'll remove that as well.

2021-08-05 20:37 UTC, JPrevost commented on app/mailers/report_mailer.rb
> +         to: ENV['THESIS_ADMIN_EMAIL'],
Hmmm. I think we do need that right so we can set the URL to the preferred URL and not the herokuapp version for staging/prod?

2021-08-05 20:42 UTC, JPrevost commented on app/mailers/report_mailer.rb
> +         to: ENV['THESIS_ADMIN_EMAIL'],
Oh, I see. You used preferred domain. never mind. Good idea.

2021-08-05 20:43 UTC, jazairi commented on app/mailers/report_mailer.rb
> +         to: ENV['THESIS_ADMIN_EMAIL'],
`PREFERRED_DOMAIN` exists in staging and prod for that purpose. It's currently the first choice for the default_url config in production.rb, so the URLs should appear as expected.

2021-08-05 20:47 UTC, JPrevost approved these changes

2021-08-05 20:58 UTC, merged